### ISSUE TITLE
Missing text in `local_pandoc_version()`

### ISSUE THREAD

**Issue by gadenbuie** [cderv/pandoc#14]
```r
> pandoc::local_pandoc_version("2.13")

1: yes
2: no

Selection:
```

```r
> pandoc::pandoc_activate("2.13")
ℹ Version '2.13' is not yet installed
! Would you like to install it ?

1: yes
2: no

Selection:
```

I think because `suppressMessages()` hides the prompt output but then `pandoc_activate()` still needs to ask if the missing version should be installed so only the options/input are shown.

https://github.com/cderv/pandoc/blob/1c57a064ed5615b00bbc689bac7bdb6d42f4c8ec/R/pandoc-run.R#L60

**Comment by cderv** [comment]
I think I should probably allow activating a version that is already install and let user install it in another step using `pandoc_install()`. Does that sound ok to you ?

**Comment by gadenbuie** [comment]
I certainly see some value in letting users call e.g. `pandoc::local_pandoc_version("2.13")` in a way that will also go ahead and install 2.13 for them, provided that they've opted into that behavior. So maybe with an extra arg, e.g. `install = TRUE` or `prompt = FALSE`.

That said, as a package maintainer, I'd say you have a nice separation of concerns and it'll probably be easier to maintain the stricter version that would require this:

```r
pandoc_install("2.13")
local_pandoc_version("2.13")
```

**Comment by cderv** [comment]
I'll think about it and try the `install = TRUE` approach to see.

> That said, as a package maintainer, I'd say you have a nice separation of concerns

Yeah I went with the user way in mind at first but maybe I'll go back the maintainer first approach 😄

**Comment by cderv** [comment]
I am wondering why I need this `suppressMessages()` in the first place 🤔 
I am thinking of removing it completely.

We would have 

* if run interactively, 
````r
> local_pandoc_version("2.11.4")
i Version '2.11.4' is not yet installed
! Would you like to install it ?

1: yes
2: no

Sélection : 1
i Fetching Pandoc releases info from github...
i Installing Pandoc release 2.11.4
  Downloading bundle...
√ Pandoc version 2.11.4 installed.
Setting global deferred event(s).
i These will be run:
  * Automatically, when the R session ends.
  * On demand, if you call `withr::deferred_run()`.
i Use `withr::deferred_clear()` to clear them without executing.

> local_pandoc_version("2.7.3")
i Version '2.7.3' is not yet installed
! Would you like to install it ?

1: yes
2: no

Sélection : 2
Error in `pandoc_is_installed()` at pandoc/R/pandoc-activate.R:38:6:
! Version '2.7.3' is not yet installed
Run `rlang::last_error()` to see where the error occurred.
````

* if not interactive
````r
> options(rlang_interactive = FALSE)
> local_pandoc_version("2.7.3")
Error in `pandoc_is_installed()` at pandoc/R/pandoc-activate.R:38:6:
! Version '2.7.3' is not yet installed
Backtrace:
    x
 1. \-pandoc::local_pandoc_version("2.7.3")
 2.   \-pandoc::pandoc_activate(version, rmarkdown = rmarkdown, quiet = TRUE) at pandoc/R/pandoc-run.R:60:2
 3.     \-pandoc::pandoc_is_installed(version, error = TRUE, ask = rlang::is_interactive()) at pandoc/R/pandoc-activate.R:38:6
 4.       \-rlang::abort(sprintf("Version '%s' is not yet installed", version)) at pandoc/R/pandoc-install.R:368:6
````

And nothing shows if called again 
````r
> local_pandoc_version("2.11.4")
````

Does it seems ok to you with this behavior ? 

`with_pandoc_version()` works this way as relying directly on `pandoc_activate()` behavior

**Comment by gadenbuie** [comment]
Yeah that looks great to me!
