### ISSUE TITLE
with_pandoc_version() is still not working to change rmarkdown used version

### ISSUE THREAD

**Issue by cderv** [cderv/pandoc#21]
![image](https://user-images.githubusercontent.com/6791940/158235998-42b7d657-5b91-4200-87d8-734ee171c85a.png)

It seems like my last change is still not working correctly. 

It is not an issue with rmarkdown rendering as it happens also in R console

````r
> with_pandoc_version("2.11.4", {
+     rmarkdown::pandoc_version()
+ })
[1] ‘2.17.1.1’
````

However, it is working correctly with function from the package

````r
> with_pandoc_version("2.11.4", {
+     pandoc::pandoc_version()
+ })
[1] ‘2.11.4’
````

**Comment by cderv** [comment]
I remember now that I added `rmarkdown = TRUE` argument. 🤔 Is this a good idea to set it to FALSE by default ?

**Comment by gadenbuie** [comment]
> Is this a good idea to set it to FALSE by default ?

I'd expect `rmarkdown = TRUE` to be the default, since I'd often want to call `pandoc::local_pandoc_version()` to test how an output from `rmarkdown::render()` works under different pandoc versions.

**Comment by cderv** [comment]
yeah that is useful. I usually use `pandoc_activate()` directly, and I have set the default to TRUE in there. 

The challenge to make this stable, is to properly deactivate the version set for rmarkdown to use. I am think of adding a new mechanism in rmarkdown to avoid this `rmarkdown::find_pandoc()` danse. 🤔
